/**
 * Uploads all PNG images from public/ to Vercel Blob storage
 * and writes a blob URL map to src/blob-urls.ts.
 *
 * Usage: npx tsx scripts/upload-blobs.ts
 * Requires: BLOB_READ_WRITE_TOKEN in .env.local or environment
 */

import { readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { put } from '@vercel/blob';

const ROOT_DIR = join(import.meta.dirname, '..');
const PUBLIC_DIR = join(ROOT_DIR, 'public');
const OUTPUT_FILE = join(ROOT_DIR, 'src', 'blob-urls.ts');
const ENV_FILE = join(ROOT_DIR, '.env.local');

function loadEnvFile(filePath: string): void {
  if (!existsSync(filePath)) return;
  const content = readFileSync(filePath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex);
    const raw = trimmed.slice(eqIndex + 1);
    // Strip surrounding quotes if present
    const value = raw.replace(/^["']|["']$/g, '');
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

async function main(): Promise<void> {
  loadEnvFile(ENV_FILE);

  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      'BLOB_READ_WRITE_TOKEN is not set. Run `vercel env pull .env.local` first.',
    );
  }

  const files = readdirSync(PUBLIC_DIR).filter((f) => f.endsWith('.png'));
  console.log(`Uploading ${String(files.length)} images to Vercel Blob...`);

  const urlMap: Record<string, string> = {};

  for (const file of files) {
    const filePath = join(PUBLIC_DIR, file);
    const content = readFileSync(filePath);

    const blob = await put(`paperclip-clicker/${file}`, content, {
      access: 'public',
      addRandomSuffix: false,
      token,
      contentType: 'image/png',
    });

    urlMap[`/${file}`] = blob.url;
    console.log(`  ✓ ${file} → ${blob.url}`);
  }

  // Generate the TypeScript module
  const entries = Object.entries(urlMap)
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
    .map(([key, url]) => `  '${key}': '${url}',`)
    .join('\n');

  const output = `// Auto-generated by scripts/upload-blobs.ts — do not edit manually
const BLOB_URLS: Record<string, string> = {
${entries}
} as const;

/**
 * Resolves a local image path to its Vercel Blob URL.
 * Falls back to the local path in development.
 */
export function blobUrl(localPath: string): string {
  return BLOB_URLS[localPath] ?? localPath;
}
`;

  writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`\nWrote blob URL map to ${OUTPUT_FILE}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
