// Auto-generated by scripts/upload-blobs.ts — do not edit manually
const BLOB_URLS: Record<string, string> = {
  '/1.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/1.png',
  '/2.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/2.png',
  '/3.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/3.png',
  '/4.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/4.png',
  '/5.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/5.png',
  '/6.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/6.png',
  '/7.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/7.png',
  '/8.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/8.png',
  '/9.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/9.png',
  '/10.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/10.png',
  '/11.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/11.png',
  '/12.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/12.png',
  '/13.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/13.png',
  '/14.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/14.png',
  '/15.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/15.png',
  '/16.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/16.png',
  '/17.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/17.png',
  '/18.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/18.png',
  '/19.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/19.png',
  '/20.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/20.png',
  '/background.png': 'https://2lpygtw3cqth2vaa.public.blob.vercel-storage.com/paperclip-clicker/background.png',
} as const;

/**
 * Resolves a local image path to its Vercel Blob URL.
 * Falls back to the local path in development.
 */
export function blobUrl(localPath: string): string {
  return BLOB_URLS[localPath] ?? localPath;
}
